# Generated by Django 4.2.7 on 2023-12-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_expensecategory_user_incomecategory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltransaction',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('Доход', 'Доход'), ('Расход', 'Расход'), ('Перевод', 'Перевод')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('Доход', 'Доход'), ('Расход', 'Расход'), ('Перевод', 'Перевод')], max_length=10, null=True),
        ),
    ]
