# Generated by Django 4.2.7 on 2023-11-06 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_account_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='currency',
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
